services:
  frontend:
    build:
      context: ./fe-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network
    volumes:
      - ./fe-app:/app
      - /app/node_modules

  backend:
    build:
      context: ./be-app
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network
    volumes:
      - ./be-app:/app
      - /app/node_modules

networks:
  app-network:
    driver: bridge
